// packages/react/src/client/LegalNotice/index.tsx
"use client";

import { type LegalNoticeProps } from "@incubateur-ademe/legal-pages-markdown";
import LegalNoticeHtml from "@incubateur-ademe/legal-pages-markdown/html/LegalNotice.html?raw";
import { type ReactNode, useId } from "react";

import { legalNoticeDefaultProps, LegalNoticeThirdPartyText } from "../../LegalNotice";
import { ClientOnly } from "../../utils/ClientOnly";
import { ClientPortal } from "../../utils/ClientPortal";
import { useHtmlParser } from "../useHtmlParser";

export type LegalNoticeClientProps = Omit<LegalNoticeProps<ReactNode>, "includeBetaGouv">;

export const LegalNoticeClient = ({
  date = legalNoticeDefaultProps.date,
  siteName,
  thirdParties = legalNoticeDefaultProps.thirdParties,
  elementThirdParties,
  licenceUrl,
  privacyPolicyUrl = legalNoticeDefaultProps.privacyPolicyUrl,
  siteHost,
  siteUrl,
  contactEmail,
}: LegalNoticeClientProps) => {
  const elementThirdPartiesPortalId = useId();

  return (
    <>
      <div
        dangerouslySetInnerHTML={{
          __html: useHtmlParser(LegalNoticeHtml, {
            date,
            siteName,
            elementThirdParties: `<div id="${elementThirdPartiesPortalId}"></div>`,
            licenceUrl,
            privacyPolicyUrl,
            siteHost,
            siteUrl,
            contactEmail,
          }),
        }}
      />
      <ClientOnly>
        <ClientPortal childrenId={elementThirdPartiesPortalId}>
          {elementThirdParties ?? <LegalNoticeThirdPartyText thirdParties={thirdParties} />}
        </ClientPortal>
      </ClientOnly>
    </>
  );
};

export default LegalNoticeClient;

// packages/vue3/src/LegalNotice/LegalNotice.vue
<script setup lang="ts">
import { type LegalNoticeProps } from "@incubateur-ademe/legal-pages-markdown";
import { shallowRef } from "vue";

import LegalNotice from "../../generated/LegalNotice.vue";
import LegalNoticeWithBeta from "../../generated/LegalNotice_withBeta.vue";
import { RELEASE_DATE } from "../releaseDate";
import LegalNoticeThirdPartyText from "./LegalNoticeThirdPartyText.vue";

const props = withDefaults(defineProps<LegalNoticeProps<object>>(), {
  date: RELEASE_DATE,
  includeBetaGouv: false,
  thirdParties: [] as never,
  privacyPolicyUrl: "/politique-de-confidentialite",
});

const refThirdParties = props.elementThirdParties ?? shallowRef(LegalNoticeThirdPartyText);
</script>

<template>
  <LegalNoticeWithBeta v-if="includeBetaGouv" v-bind="{ ...$attrs, ...$props, elementThirdParties: refThirdParties }" />
  <LegalNotice v-else v-bind="{ ...$attrs, ...$props, elementThirdParties: refThirdParties }" />
</template>
