// packages/vue3/src/CookiesPolicy/CookiesPolicy.vue
<script setup lang="ts">
import { type CookiesPolicyProps } from "@incubateur-ademe/legal-pages-markdown";

import CookiesPolicy from "../../generated/CookiesPolicy.vue";
import CookiesPolicyWithBeta from "../../generated/CookiesPolicy_withBeta.vue";
import { RELEASE_DATE } from "../releaseDate";

withDefaults(defineProps<CookiesPolicyProps<object>>(), {
  includeBetaGouv: false,
  date: RELEASE_DATE,
});
</script>

<template>
  <CookiesPolicyWithBeta v-if="includeBetaGouv" v-bind="{ ...$attrs, ...$props }" />
  <CookiesPolicy v-else v-bind="{ ...$attrs, ...$props }" />
</template>

// packages/react/src/CookiesPolicy/index.tsx
import { type CookiesPolicyProps } from "@incubateur-ademe/legal-pages-markdown";
import { useId } from "react";

import { RELEASE_DATE } from "../releaseDate";
import { ClientOnly } from "../utils/ClientOnly";
import { ClientPortal } from "../utils/ClientPortal";
import { htmlParser } from "../utils/htmlParser";

export { type CookiesPolicyProps };

export const CookiesPolicy = async ({
  date = RELEASE_DATE,
  includeBetaGouv = false,
  cookieConsentButton,
  siteName,
  analyticTool,
}: CookiesPolicyProps<React.ReactNode>) => {
  const buttonPortalId = useId();

  return (
    <>
      <div
        dangerouslySetInnerHTML={{
          __html: await htmlParser("CookiesPolicy", {
            date,
            includeBetaGouv,
            siteName,
            cookieConsentButton: `<span id="${buttonPortalId}"></span>`,
            analyticTool,
          }),
        }}
      />
      <ClientOnly>
        <ClientPortal childrenId={buttonPortalId}>{cookieConsentButton}</ClientPortal>
      </ClientOnly>
    </>
  );
};

export default CookiesPolicy;
