// packages/vue3/src/LegalNotice/LegalNotice.vue
<script setup lang="ts">
import { type LegalNoticeProps } from "@incubateur-ademe/legal-pages-markdown";
import { shallowRef } from "vue";

import LegalNotice from "../../generated/LegalNotice.vue";
import LegalNoticeWithBeta from "../../generated/LegalNotice_withBeta.vue";
import { RELEASE_DATE } from "../releaseDate";
import LegalNoticeThirdPartyText from "./LegalNoticeThirdPartyText.vue";

const props = withDefaults(defineProps<LegalNoticeProps<object>>(), {
  date: RELEASE_DATE,
  includeBetaGouv: false,
  thirdParties: [] as never,
  privacyPolicyUrl: "/politique-de-confidentialite",
});

const refThirdParties = props.elementThirdParties ?? shallowRef(LegalNoticeThirdPartyText);
</script>

<template>
  <LegalNoticeWithBeta v-if="includeBetaGouv" v-bind="{ ...$attrs, ...$props, elementThirdParties: refThirdParties }" />
  <LegalNotice v-else v-bind="{ ...$attrs, ...$props, elementThirdParties: refThirdParties }" />
</template>

// packages/react/src/LegalNotice/index.tsx
import { type LegalNoticeProps } from "@incubateur-ademe/legal-pages-markdown";
import { type ReactNode, useId } from "react";

import { RELEASE_DATE } from "../releaseDate";
import { ClientOnly } from "../utils/ClientOnly";
import { ClientPortal } from "../utils/ClientPortal";
import { htmlParser } from "../utils/htmlParser";

export { type LegalNoticeProps };

export const LegalNoticeThirdPartyText = ({ thirdParties }: Required<Pick<LegalNoticeProps, "thirdParties">>) => (
  <>
    {thirdParties.length ? (
      thirdParties.map(({ name, url, text }, index) => (
        <p key={index}>
          {text}{" "}
          <a href={url} target="_blank" rel="noopener noreferrer">
            {name}
          </a>
        </p>
      ))
    ) : (
      <p>Aucun tiers n'est utilisé sur ce site.</p>
    )}
  </>
);

export const legalNoticeDefaultProps = {
  date: RELEASE_DATE,
  thirdParties: [],
  privacyPolicyUrl: "/politique-de-confidentialite",
};

export const LegalNotice = async ({
  date = legalNoticeDefaultProps.date,
  includeBetaGouv = false,
  siteName,
  thirdParties = legalNoticeDefaultProps.thirdParties,
  elementThirdParties,
  licenceUrl,
  privacyPolicyUrl = legalNoticeDefaultProps.privacyPolicyUrl,
  siteHost,
  siteUrl,
  contactEmail,
}: LegalNoticeProps<ReactNode>) => {
  const elementThirdPartiesPortalId = useId();

  return (
    <>
      <div
        dangerouslySetInnerHTML={{
          __html: await htmlParser("LegalNotice", {
            date,
            includeBetaGouv,
            siteName,
            elementThirdParties: `<div id="${elementThirdPartiesPortalId}"></div>`,
            licenceUrl,
            privacyPolicyUrl,
            siteHost,
            siteUrl,
            contactEmail,
          }),
        }}
      />
      <ClientOnly>
        <ClientPortal childrenId={elementThirdPartiesPortalId}>
          {elementThirdParties ?? <LegalNoticeThirdPartyText thirdParties={thirdParties} />}
        </ClientPortal>
      </ClientOnly>
    </>
  );
};

export default LegalNotice;
