// examples/react-next/src/app/politique-des-cookies/page.tsx
import { fr } from "@codegouvfr/react-dsfr";
import { CookiesPolicy } from "@incubateur-ademe/legal-pages-react/CookiesPolicy";

import { CookieConsentButton } from "../CookieConsentButton";

// eslint-disable-next-line import/no-default-export
export default function CookiePolicyPage() {
  return (
    <div className={fr.cx("fr-container", "fr-my-4w")}>
      <CookiesPolicy
        analyticTool={{
          name: "Matomo",
          cookieListUrl: "https://matomo.org/faq/general/faq_146/",
          policyUrl: "https://matomo.org/privacy-policy/",
        }}
        cookieConsentButton={<CookieConsentButton>CLICK</CookieConsentButton>}
        siteName="SITE EXAMPLE"
      />
    </div>
  );
}

// examples/vue3/src/views/PolitiqueDesCookies.vue
<script setup lang="ts">
import { CookiesPolicy, type CookiesPolicyPropsAnalyticTool } from '@incubateur-ademe/legal-pages-vue3'
import CookieConsentButton from '@/components/CookieConsentButton.vue'

const cookieConsentButton = shallowRef(CookieConsentButton)

function onCookieConsentClick () {
  // eslint-disable-next-line no-console
  console.log('====== CLICK')
}

const analyticTool: CookiesPolicyPropsAnalyticTool = {
  name: 'Matomo',
  cookieListUrl: 'https://matomo.org/faq/general/faq_146/',
  policyUrl: 'https://matomo.org/privacy-policy/',
}
</script>

<template>
  <div class="fr-container fr-my-4w">
    <CookiesPolicy
      site-name="SITE EXEMPLE"
      :cookie-consent-button="cookieConsentButton"
      :analytic-tool="analyticTool"
      @child-clicked="onCookieConsentClick"
    />
  </div>
</template>
