// packages/react/src/client/PrivacyPolicy/index.tsx
"use client";

import { type PrivacyPolicyProps } from "@incubateur-ademe/legal-pages-markdown";
import PrivacyPolicyHtml from "@incubateur-ademe/legal-pages-markdown/html/PrivacyPolicy.html?raw";
import { useId } from "react";

import { PrivacyPolicyCookieTable, privacyPolicyDefaultProps, PrivacyPolicyThirdPartyTable } from "../../PrivacyPolicy";
import { ClientOnly } from "../../utils/ClientOnly";
import { ClientPortal } from "../../utils/ClientPortal";
import { useHtmlParser } from "../useHtmlParser";

export type PrivacyPolicyClientProps = PrivacyPolicyProps;

export const PrivacyPolicyClient = ({
  date = privacyPolicyDefaultProps.date,
  cookieConsentButton,
  siteName,
  thirdParties = privacyPolicyDefaultProps.thirdParties,
  tableThirdParties,
  cookies = privacyPolicyDefaultProps.cookies,
  tableCookies,
}: PrivacyPolicyClientProps) => {
  const buttonPortalId = useId();
  const tableThirdPartiesPortalId = useId();
  const tableCookiesPortalId = useId();

  return (
    <>
      <div
        dangerouslySetInnerHTML={{
          __html: useHtmlParser(PrivacyPolicyHtml, {
            date,
            siteName,
            cookieConsentButton: `<span id="${buttonPortalId}"></span>`,
            tableThirdParties: `<div id="${tableThirdPartiesPortalId}"></div>`,
            tableCookies: `<div id="${tableCookiesPortalId}"></div>`,
          }),
        }}
      />
      <ClientOnly>
        <ClientPortal childrenId={buttonPortalId}>{cookieConsentButton}</ClientPortal>
        <ClientPortal childrenId={tableThirdPartiesPortalId}>
          {tableThirdParties ?? <PrivacyPolicyThirdPartyTable thirdParties={thirdParties} />}
        </ClientPortal>
        <ClientPortal childrenId={tableCookiesPortalId}>
          {tableCookies ?? <PrivacyPolicyCookieTable cookies={cookies} />}
        </ClientPortal>
      </ClientOnly>
    </>
  );
};

export default PrivacyPolicyClient;

// packages/vue3/src/PrivacyPolicy/PrivacyPolicy.vue
<script setup lang="ts">
import { type PrivacyPolicyProps } from "@incubateur-ademe/legal-pages-markdown";
import { shallowRef } from "vue";

import PrivacyPolicy from "@/generated/PrivacyPolicy.vue";

import { RELEASE_DATE } from "../releaseDate";
import PrivacyPolicyCookieTable from "./PrivacyPolicyCookieTable.vue";
import PrivacyPolicyThirdPartyTable from "./PrivacyPolicyThirdPartyTable.vue";

const props = withDefaults(defineProps<PrivacyPolicyProps<object>>(), {
  date: RELEASE_DATE,
  includeBetaGouv: false,
  thirdParties: [] as never,
  cookies: [] as never,
});

const refTableCookies = props.tableCookies ?? shallowRef(PrivacyPolicyCookieTable);
const refTableThirdParties = props.tableThirdParties ?? shallowRef(PrivacyPolicyThirdPartyTable);
</script>

<template>
  <PrivacyPolicy
    v-bind="{ ...$attrs, ...$props, tableCookies: refTableCookies, tableThirdParties: refTableThirdParties }"
  />
</template>
